# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_data', models.TextField()),
                ('x', models.CharField(max_length=10)),
                ('y', models.CharField(max_length=10)),
                ('angle', models.CharField(max_length=10)),
            ],
        ),
    ]
